name: Deploy CuteBunnyWebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # this tells GitHub to use your self-hosted runner

    steps:
      # Step 1: Check out your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build \
            -t cutebunnywebapp:latest \
            -f CuteBunnyWebApp/Dockerfile \
            CuteBunnyWebApp

      # Step 3: Stop & remove the old container if it exists
      - name: Stop old container
        run: docker rm -f cutebunnywebapp || true

      # Step 4: Run the new container with secrets
      - name: Run new container
        run: |
          docker run -d --restart=always -p 7001:80 \
            --name cutebunnywebapp \
            -e APP_KEY="${{ secrets.APP_KEY }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_DATABASE="${{ secrets.DB_DATABASE }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e BING_IMAGE_SEARCH_API_KEY="${{ secrets.BING_API_KEY }}" \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e TWILIO_SENDER_PHONE_NUMBER="${{ secrets.TWILIO_SENDER_PHONE_NUMBER }}" \
            -e TWILIO_RECEIVING_PHONE_NUMBER="${{ secrets.TWILIO_RECEIVING_PHONE_NUMBER }}" \
            -e TWILIO_ACCOUNT_SID="${{ secrets.TWILIO_ACCOUNT_SID }}" \
            -e TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}" \
            cutebunnywebapp:latest

      # Step 5: Run database migrations (optional, if Laravel or similar)
      - name: Run Migrations
        run: docker exec cutebunnywebapp php artisan migrate --force

      # Step 6: Prune old Docker images (optional)
      - name: Prune old Docker images
        run: docker image prune -f
